apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}
data:
  myvalue: "Hello world"
  drink: {{ .Values.favoriteDrink | default (printf "%s-tea" (include "mychart.fullname" .)) }}
