namespace: my-namespace
namePrefix: dev-
nameSuffix: "-001"
commonLabels:
  app: bingo
commonAnnotations:
  onCallPager: 800-555-1212
resources:
- deployment.yaml
images:
- name: nginx
  newName: my.image.registry/nginx
  newTag: 1.4.0
patchesStrategicMerge:
- set_memory.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-deployment
  path: patch.yaml

configMapGenerator:
- name: example-configmap-1
  files:
  - application.properties

secretGenerator:
- name: example-secret-1
  files:
  - password.txt

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
